apiVersion: v1
kind: ConfigMap
metadata:
  name: ecoreport-config
  namespace: ecoreport
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "wastecycle"
  DB_USER: "postgres"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  JWT_EXPIRES_IN: "30d"
